### ISSUE TITLE
[Feature Request] Configurable time partitioning size

### ISSUE THREAD

**Issue by GrgDev** [anelendata/target-bigquery#2]
Partitioning is currently hardcoded to Day.
https://github.com/anelendata/target-bigquery/blob/master/target_bigquery/__init__.py#L49

BigQuery supports partitioning by Hour, Day, Month, and Year. I would propose that a new optional configuration value is supported that allows the declaration of one of these values. This configuration value being excluded would default back to Day assuming the "partition_by" field is still present in the config.

PS: This bigquery target tool is still great! Love it.

**Comment by daigotanaka** [comment]
Thx for posting the request. Both of them are good points! I cannot promise when I can work on this right now. If you have the bandwidth to create a PR, I'm more than happy to have you onboard as a collaborator :) Otherwise, let me see when I can work on it. Thx for your patience and support :)

**Comment by daigotanaka** [comment]
(another driver towards those improvements, of course, is when I will have similar needs to do my own client's job ;)

**Comment by daigotanaka** [comment]
@GrgDev Actually, I drafted #4 to implement this. If you can test this out, great, otherwise, I will find time to test this before merging and releasing the new version.

**Comment by GrgDev** [comment]
I don't have immediate bandwidth because right now I am trying to get our first Airflow DAG setup that uses this in Google Composer and dealing with the Python dependencies has been tricky. Resorting to the Virtual Python Environment Operator to do this because of the version conflict on the jsonschema dependency with the Composer environment. Don't know an easy way to try your change that cannot be handled by an easy pip install of the package.

**Comment by GrgDev** [comment]
But after I get that DAG running, I can try to set up something local for testing.
